<a href="https://colab.research.google.com/github/JosuePerezValenzuela/ML_Module2/blob/master/ML_M2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Installing TensorFlow
To install TensorFlow on your local machine you can use pip.
```console
pip install tensorflow
```

If you have a CUDA enabled GPU you can install the GPU version of TensorFlow. You will also need to install some other software which can be found here: https://www.tensorflow.org/install/gpu
```console
pip install tensorflow-gpu
```

In [3]:
import tensorflow as tf  # importar
print(tf.version)  # Version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## **TensorFlow introduction**
Que es un tensor?
Basicamente un vector y/o matrices a dimeciones altas, TensorFlow representa tensores como matrices de n dimensiones de tipos de datos base
Cada tensor tiene:
  Data types unclude: float32, int32, String and others
  Shape: Represents the dimension of data

# Creacion de tensores

https://www.tensorflow.org/api_docs/python/tf/dtypes/DType?version=stable

In [4]:
# nombre = tf.Variable(<Valor>, tf.<tipoDeDato>)
string = tf.Variable("This is a String", tf.string)
number = tf.Variable(10, tf.int16)
floatin = tf.Variable(10.0, tf.float64)
#Estos son escalares o tensores de rank 0 eso significa solo un valor

#Rank/Degree of tensors

Rank == Degree -> Estos terminos hacen referencia al numero de dimensiones que tiene un tensor

A continuacion la creacion de tensores de mayor "rank"

In [20]:
# Aqui ya tiene un arreglo en lugar de simplemente una "variable"
rank1_tensor = tf.Variable(["Test", "Hello", "Como estan gentita?"], tf.string)

#En este se tiene un arreglo de arreglos, osea una matriz
rank2_tensor = tf.Variable([["Test", "ok", "3"], ["Test", "2", "3"]], tf.string)

#Determinar el "rank" de un tensor

In [16]:
tf.rank(rank2_tensor)
#numpy = 2 -> indica que es un tensor de rank = 2

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#Shape de un tensor

Es el numero de elementos que existe en cada dimension, en algunas ocaciones puede ser "unknown"

In [21]:
# 2 arreglos, cada una de 3 elementos
rank2_tensor.shape

TensorShape([2, 3])

#Cambiar el shape


In [26]:
tensor1 = tf.ones([1, 2, 3]) # Crea una lista que tiene 2 listas de cada una de 3 elementos (Lleno de unos)
tensor2 = tf.reshape(tensor1, [2, 3, 1]) #reshape los datos existentes a [2, 3, 1] -> una lista que tiene 2 listas que tiene 3 listas de un elemto
tensor3 = tf.reshape(tensor2, [3, -1]) # -1 indica al tensor que debe calcular el tamaño de la dimension en ese lugar, en este caso como tenemos 6 elementos
                                       # y decimos que queremos tener 3 arreglos sera 6 / 3 = 2 en cada arreglo

In [27]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


#Slicing tensors
Puede ser usado en tensores para seleccionar un eje o elementos especificos

Una vez cortados los tensores podemos darle un nombre a cada dimension del tensor que cortamos

Ej: tensor[dim1, dim2, dim3]

In [29]:
#Matriz 2D
matrix = [[1, 2, 3, 4 ,5],
          [6, 7, 8, 9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20]]

tensor = tf.Variable(matrix, dtype = tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [30]:
#Seleccionaremos diferentes columans y filas del tensor usando "slicing"

three = tensor[0, 2] #Devuelve el tercer elemento de la primera lista
print(three)

fila1 = tensor[0] #Retorna al primera fila
print(fila1)

columna1 = tensor[:, 0] #Selecciona la primera columna
print(columna1)

fila_2_and_4 = tensor[1::2] #Selecciona la segunda y cuarta fila
print(fila_2_and_4)

columna_1_in_row_2_and_3 = tensor[1:3, 0]
print(columna_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


#Tipos de tensores

Hay diferentes tipos de tensores, estos son los mas usados

Variable

Constant

Placeholder

SparseTensor

Con la excepcion de "Variable" los demas son inmutables

#Evaluacion de un tensor

Existen alguans veces en las que debemos evaluar a un tensor, hay distintas formas, la mas facil

In [ ]:
with tf.Session() as sess: #Crea una sesion usando el grafo por defecto
  tensor.eval()